version: '2'
services:
  local:
    container_name: local
    build: .
    stdin_open: true
    volumes:
      - .:/app
      - gradle_cache:/root/.gradle
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      cluster_env: 'LOCAL'
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: developer
      DB_PASSWORD: mysecretpassword
    depends_on:
      - db
    working_dir: /app
    command: gradle bootRun
  db:
    image: postgres:9.4
    container_name: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/case_data
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_db:/var/lib/postgresql/data/case_data
    ports:
      - "5440:5432"
volumes:
  gradle_cache:
  postgres_db: